image: strongboxci/alpine:jdk8-mvn3.6

tasks:
  - name: Build Strongbox
    command: mvn install -DskipTests=false
  - name: Start Strongbox
    command: cd strongbox-web-core && mvn spring-boot:run

ports:
  - port: 48080