image: strongboxci/alpine:jdk8-mvn3.6

tasks:
  - init: Get settings.xml
    command: mkdir -p ~/.m2/ && curl -o ~/.m2/settings.xml https://strongbox.github.io/assets/resources/maven/settings.xml
  - name: Build Strongbox
    command: mvn install -DskipTests=false
  - name: Start Strongbox
    command: cd strongbox-web-core && mvn spring-boot:run

ports:
  - port: 48080