tasks:
  - init: Configure maven settings.xml
    command: mkdir -p ~/.m2/ && curl -o ~/.m2/settings.xml https://strongbox.github.io/assets/resources/maven/settings.xml
  - init: Install JDK8
    command: sdk i java 8.0.265-open
  - name: Build Strongbox
    command: mvn install -DskipTests=false
  - name: Start Strongbox
    command: cd strongbox-web-core && mvn spring-boot:run

ports:
  - port: 48080