image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build and run Strongbox
    init: mvn install -DskipTests && cd strongbox-web-core && mvn spring-boot:run

ports:
  - port: 48080
    onOpen: open-preview
  - port: 1000-65535
    onOpen: ignore