image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build and run Strongbox
    init: mvn install -DskipTests && mvn -pl ./strongbox-web-core spring-boot:run

ports:
  - port: 48080
    onOpen: open-preview
  - port: 1000-48000
    onOpen: ignore
  - port: 49000-65535
    onOpen: ignore